# Site settings
author: Michael Piercy
title: 
header-img: img/home-bg.png
email: michael.piercy@zoho.com
copyright_name: Michael Piercy
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: MichaelPiercy14
github_username:  Michael-Piercy

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
